### ISSUE TITLE
Error when registering new account

### ISSUE THREAD

**Issue by mertoral** [lucabriguglia/Atlas#1]
# Summary

On create new account form, user enters valid email address and a password that meets complexity requirements. 

When the form is submitted following error displayed:

![image](https://user-images.githubusercontent.com/4994432/89992386-1afc8180-dc7d-11ea-9b4c-36a4d85fea64.png)

**Comment by lucabriguglia** [comment]
There is something wrong with the mail service, investigating...

**Comment by lucabriguglia** [comment]
It's a SMTP exception.

**Comment by lucabriguglia** [comment]
Issue has been resolved, you can now register to the demo site.

**Comment by mertoral** [comment]
Test evidence?  Alright then.. Like the project.. I'll throw in one
![image](https://user-images.githubusercontent.com/4994432/89996198-6b2a1280-dc82-11ea-9cba-5ae5ef814f22.png)

**Comment by mertoral** [comment]
Test evidence? I'll throw in one...
![image](https://user-images.githubusercontent.com/4994432/89996348-97459380-dc82-11ea-9182-e1ab070f8307.png)
