### ISSUE TITLE
File Nesting

### ISSUE THREAD

**Issue by 274188A** [lucabriguglia/Atlas#2]
Just wondering if you've considered using file nesting in the organization of c# code for razor pages? 

eg the `ForumPage.cs` could be renamed to `Forum.razor.cs` and be nested under the razor page.  Just a convenience thing.

**Comment by lucabriguglia** [comment]
Yes, I have considered it but I preferred not to so all "code behind" is under `Components` for consistency since I couldn't do it for theme components.
