### ISSUE TITLE
using async to add Event

### ISSUE THREAD

**Issue by 274188A** [lucabriguglia/Atlas#3]
really enjoying see the ideas here -  not really an issue but noticed the code that adds to the Events could be using the `async` if you preferred to - for example: 

`await _dbContext.Events.AddAsync(new Event(command.SiteId,...`

**Comment by lucabriguglia** [comment]
Thanks @274188A! Add vs AddAsync has been always source of controversy. According to the official documentation for AddAsync:
```
This method is async only to allow special value generators, such as the one used by 'Microsoft.EntityFrameworkCore.Metadata.SqlServerValueGenerationStrategy.SequenceHiLo', to access the database asynchronously. For all other cases the non async method should be used.
```
I think in our scenario Add should be preferred over AddAsync.
