### ISSUE TITLE
Formatting Dates

### ISSUE THREAD

**Issue by 274188A** [lucabriguglia/Atlas#7]
For those of us using a `d/mm/yy` format to display dates the `DateTimeExtensions` class provides a utc to local date value conversion - although not the option to formatting.

Any ideas on the best approach?

If date formats are specified in the *.resx files I guess they could be read out and used there in the DateTimeExtensions class.

So for example instead of this:

`var forumDate = localDate.ToShortDateString();`

use this:

rm is the instantiation of the resource management eg [https://www.c-sharpcorner.com/UploadFile/65794e/how-to-read-resx-file-in-c-sharp/](https://www.c-sharpcorner.com/UploadFile/65794e/how-to-read-resx-file-in-c-sharp/)

`var forumDate = localDate.ToString(rm.ShortDateFormat);`

**Comment by 274188A** [comment]
just seen line 62 in atlas.client.program

**Comment by 274188A** [comment]
ok, now understand - language field in the site table defines the current culture

**Comment by lucabriguglia** [comment]
No problem @274188A, I'm glad you like the project :-)
